/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		       var X = 0
		       var Y = 0
		       var Timer = java.util.Random().nextLong(2000L,4000L)
		       var StartingMillis = 0L
		       var ShouldSync = false
		
			    fun setCellCoords( )  {
		     		val coords = name.replace("firefly_","").split("_")   
		     		X  = coords[0].toInt()
		     		Y  = coords[1].toInt()
		  		}
		
		       fun checkSyncTime() : Boolean {
		           return System.currentTimeMillis() - StartingMillis >= 10000L
		       }
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
						        	setCellCoords()
						          	StartingMillis = System.currentTimeMillis()
						CommUtils.outmagenta("$name | coord=($X,0) Timer=$Timer")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="flashON",cond=whenEvent("globalStart"))
				}	 
				state("flashON") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | [IND] ON")
						forward("cellstate", "cellstate($X,0,1)" ,"griddisplay" ) 
						 ShouldSync = checkSyncTime()  
						if(  ShouldSync  
						 ){forward("synch_up", "synch_up(synch)" ,name ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashON", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashON", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="flashOFF",cond=whenTimeout("local_tout_"+name+"_flashON"))   
					transition(edgeName="t02",targetState="startSync",cond=whenDispatch("synch_up"))
				}	 
				state("flashOFF") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | [IND] OFF")
						forward("cellstate", "cellstate($X,0,0)" ,"griddisplay" ) 
						 ShouldSync = checkSyncTime()  
						if(  ShouldSync  
						 ){forward("synch_up", "synch_up(synch)" ,name ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashOFF", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashOFF", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="flashON",cond=whenTimeout("local_tout_"+name+"_flashOFF"))   
					transition(edgeName="t04",targetState="startSync",cond=whenDispatch("synch_up"))
				}	 
				state("startSync") { //this:State
					action { //it:State
						CommUtils.outblue("$name | entering SYNC mode")
						forward("cellstate", "cellstate($X,0,1)" ,"griddisplay" ) 
						emit("outerFlash", "outerFlash($Timer)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_startSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_startSync", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t05",targetState="flashOFFSync",cond=whenTimeout("local_tout_"+name+"_startSync"))   
				}	 
				state("flashONSync") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [SYNC] ON  Timer=$Timer")
						forward("cellstate", "cellstate($X,0,1)" ,"griddisplay" ) 
						emit("outerFlash", "outerFlash($Timer)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashONSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashONSync", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t06",targetState="flashOFFSync",cond=whenTimeout("local_tout_"+name+"_flashONSync"))   
				}	 
				state("flashOFFSync") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [SYNC] OFF Timer=$Timer")
						forward("cellstate", "cellstate($X,0,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashOFFSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashOFFSync", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t07",targetState="flashONSync",cond=whenTimeout("local_tout_"+name+"_flashOFFSync"))   
					transition(edgeName="t08",targetState="absorbWhileOFF",cond=whenEvent("outerFlash"))
				}	 
				state("absorbWhileOFF") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] absorbing")
						if( checkMsgContent( Term.createTerm("outerFlash(T)"), Term.createTerm("outerFlash(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val incomingTimer = payloadArg(0).toString().toLong()
								                println("$incomingTimer < $Timer ?")
								                if (incomingTimer < Timer) {
								                    Timer = incomingTimer
								                    println("$name | adopted faster timer: $Timer")
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flashONSync", cond=doswitch() )
				}	 
			}
		}
} 
