/* Generated by AN DISI Unibo */ 
package it.unibo.robot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var BodyRadius = 2.0
				
				var CurrX = 0.0 // posizione in X
				var CurrY = 0.0 // posizione in Y
				var CurrRotationDegree = 0.0 // da 0 a 359.0
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("[DDR] ready!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitCommand", cond=doswitch() )
				}	 
				state("waitCommand") { //this:State
					action { //it:State
						CommUtils.outcyan("[DDR] waiting for commands!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="rotate",cond=whenEvent("rotate"))
					transition(edgeName="t02",targetState="move",cond=whenEvent("move"))
				}	 
				state("rotate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("rotate(Degrees)"), Term.createTerm("rotate(Degrees)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var ReceivedDegrees = payloadArg(0).toString().toDouble()
												
												CurrRotationDegree = (CurrRotationDegree + ReceivedDegrees) % 360
								CommUtils.outcyan("[DDR] rotated of $ReceivedDegrees")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitCommand", cond=doswitch() )
				}	 
				state("move") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move(Distance)"), Term.createTerm("move(Distance)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var ReceivedDistance = payloadArg(0).toString().toDouble()
												
												// converti gradi in radianti
												val radians = Math.toRadians(CurrRotationDegree)
												
												// aggiorna posizione
												CurrX += ReceivedDistance * kotlin.math.cos(radians)
												CurrY += ReceivedDistance * kotlin.math.sin(radians)
								CommUtils.outcyan("[DDR] moved of $ReceivedDistance, new current position: ($CurrX, $CurrY)")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitCommand", cond=doswitch() )
				}	 
			}
		}
} 
