/* Generated by AN DISI Unibo */ 
package it.unibo.fireflies_orchestrator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Fireflies_orchestrator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var CurrBestMillis = 0L	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("[ORCHESTRATOR] Started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="orchestrate", cond=doswitch() )
				}	 
				state("orchestrate") { //this:State
					action { //it:State
						CommUtils.outblue("[ORCHESTRATOR] ready to accept messages")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_orchestrate", 
				 	 					  scope, context!!, "local_tout_"+name+"_orchestrate", 10000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="sync",cond=whenTimeout("local_tout_"+name+"_orchestrate"))   
					transition(edgeName="t01",targetState="evaluateNewFrequency",cond=whenDispatch("shareFrequency"))
				}	 
				state("evaluateNewFrequency") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("shareFrequency(Frequency)"), Term.createTerm("shareFrequency(Frequency)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            var OuterTimer = payloadArg(0).toString().toLong()
									            println("[ORCHESTRATOR] evaluating new T: $OuterTimer")
									            if (OuterTimer < CurrBestMillis || CurrBestMillis == 0L) {
									            	CurrBestMillis = OuterTimer
									            }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="orchestrate", cond=doswitch() )
				}	 
				state("sync") { //this:State
					action { //it:State
						emit("sync", "sync($CurrBestMillis)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
