/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var  TimerUntilNextToggle = 0L
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[SONAR] ready!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="measureInsufficient", cond=doswitch() )
				}	 
				state("measureInsufficient") { //this:State
					action { //it:State
						 TimerUntilNextToggle = java.util.Random().nextLong(10000L,20000L )  
						CommUtils.outyellow("[SONAR] Measure Insufficient, next sufficient will be at $TimerUntilNextToggle")
						emit("measureInsufficient", "measureInsufficient(s)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_measureInsufficient", 
				 	 					  scope, context!!, "local_tout_"+name+"_measureInsufficient", TimerUntilNextToggle )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="measureSufficient",cond=whenTimeout("local_tout_"+name+"_measureInsufficient"))   
				}	 
				state("measureSufficient") { //this:State
					action { //it:State
						 TimerUntilNextToggle = java.util.Random().nextLong(10000L,20000L )  
						CommUtils.outyellow("[SONAR] Measure Sufficient, next insufficient will be at $TimerUntilNextToggle")
						emit("measureSufficient", "measureSufficient(s)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_measureSufficient", 
				 	 					  scope, context!!, "local_tout_"+name+"_measureSufficient", TimerUntilNextToggle )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="measureInsufficient",cond=whenTimeout("local_tout_"+name+"_measureSufficient"))   
				}	 
			}
		}
} 
