/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
			   var  X          = 0
			   var  Y          = 0
			   var Timer       = java.util.Random().nextLong(2000L,4000L )
			   var OrchestratorTimer = 0L
			   var ExceedingMillis = 0L
			   
			    fun setCellCoords( )  {
		     		val coords = name.replace("firefly_","").split("_")   
		     		X  = coords[0].toInt()
		     		Y  = coords[1].toInt()
		  		}		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 setCellCoords( )                                    
						CommUtils.outmagenta("$name | X=$X Y=$Y  SharedTimer=$Timer")
						forward("shareFrequency", "shareFrequency($Timer)" ,"fireflies_orchestrator" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t05",targetState="flashON",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("flashON") { //this:State
					action { //it:State
						CommUtils.outcyan("[$name] IND ON")
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashON", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashON", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t06",targetState="flashOFF",cond=whenTimeout("local_tout_"+name+"_flashON"))   
					transition(edgeName="t07",targetState="changeTimer",cond=whenEvent("sync"))
				}	 
				state("flashOFF") { //this:State
					action { //it:State
						CommUtils.outcyan("[$name] IND OFF")
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashOFF", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashOFF", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t08",targetState="flashON",cond=whenTimeout("local_tout_"+name+"_flashOFF"))   
					transition(edgeName="t09",targetState="changeTimer",cond=whenEvent("sync"))
				}	 
				state("changeTimer") { //this:State
					action { //it:State
						CommUtils.outblue("[$name] changing timer!")
						if( checkMsgContent( Term.createTerm("sync(CurrBestMillis)"), Term.createTerm("sync(CurrBestMillis)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            OrchestratorTimer = payloadArg(0).toString().toLong()
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flashONSync", cond=doswitch() )
				}	 
				state("flashONSync") { //this:State
					action { //it:State
						CommUtils.outmagenta("[$name] SYNC ON")
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashONSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashONSync", OrchestratorTimer )  //OCT2023
					}	 	 
					 transition(edgeName="t010",targetState="flashOFFSync",cond=whenTimeout("local_tout_"+name+"_flashONSync"))   
					transition(edgeName="t011",targetState="flashOFF",cond=whenEvent("unsync"))
				}	 
				state("flashOFFSync") { //this:State
					action { //it:State
						CommUtils.outmagenta("[$name] SYNC OFF")
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flashOFFSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_flashOFFSync", OrchestratorTimer )  //OCT2023
					}	 	 
					 transition(edgeName="t012",targetState="flashONSync",cond=whenTimeout("local_tout_"+name+"_flashOFFSync"))   
					transition(edgeName="t013",targetState="flashON",cond=whenEvent("unsync"))
				}	 
			}
		}
} 
